# Generated by Django 5.1.6 on 2025-03-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('Archaea', 'Archaea'), ('Bacteria', 'Bacteria'), ('Eukarya', 'Eukarya'), ('Other', 'Other')], max_length=50)),
                ('kingdom', models.CharField(choices=[('Animalia', 'Animalia'), ('Plantae', 'Plantae'), ('Fungi', 'Fungi'), ('Protista', 'Protista'), ('Monera', 'Monera'), ('Other', 'Other')], max_length=50)),
                ('phylum', models.CharField(choices=[('Chordata', 'Chordata'), ('Arthropoda', 'Arthropoda'), ('Mollusca', 'Mollusca'), ('Echinodermata', 'Echinodermata'), ('Porifera', 'Porifera'), ('Cnidaria', 'Cnidaria'), ('Platyhelminthes', 'Platyhelminthes'), ('Nematoda', 'Nematoda'), ('Annelida', 'Annelida'), ('Bryozoa', 'Bryozoa'), ('Brachiopoda', 'Brachiopoda'), ('Chaetognatha', 'Chaetognatha'), ('Echiura', 'Echiura'), ('Hemichordata', 'Hemichordata'), ('Nemertea', 'Nemertea'), ('Onychophora', 'Onychophora'), ('Orthonectida', 'Orthonectida'), ('Phoronida', 'Phoronida'), ('Rotifera', 'Rotifera'), ('Tardigrada', 'Tardigrada'), ('Xenoturbellida', 'Xenoturbellida'), ('Other', 'Other')], max_length=50)),
                ('class_field', models.CharField(choices=[('Mammalia', 'Mammalia'), ('Aves', 'Aves'), ('Reptilia', 'Reptilia'), ('Amphibia', 'Amphibia'), ('Actinopterygii', 'Actinopterygii'), ('Chondrichthyes', 'Chondrichthyes'), ('Myxini', 'Myxini'), ('Petromyzon', 'Petromyzon'), ('Cephalaspidomorphi', 'Cephalaspidomorphi'), ('Insecta', 'Insecta'), ('Arachnida', 'Arachnida'), ('Crustacea', 'Crustacea'), ('Malacostraca', 'Malacostraca'), ('Maxillopoda', 'Maxillopoda'), ('Branchiopoda', 'Branchiopoda'), ('Ostracoda', 'Ostracoda'), ('Cephalopoda', 'Cephalopoda'), ('Gastropoda', 'Gastropoda'), ('Bivalvia', 'Bivalvia'), ('Scaphopoda', 'Scaphopoda'), ('Polyplacophora', 'Polyplacophora'), ('Monoplacophora', 'Monoplacophora'), ('Other', 'Other')], max_length=50)),
                ('order', models.CharField(choices=[('Carnivora', 'Carnivora'), ('Primates', 'Primates'), ('Rodentia', 'Rodentia'), ('Chiroptera', 'Chiroptera'), ('Passeriformes', 'Passeriformes'), ('Galliformes', 'Galliformes'), ('Anseriformes', 'Anseriformes'), ('Charadriiformes', 'Charadriiformes'), ('Falconiformes', 'Falconiformes'), ('Strigiformes', 'Strigiformes'), ('Piciformes', 'Piciformes'), ('Psittaciformes', 'Psittaciformes'), ('Columbiformes', 'Columbiformes'), ('Cuculiformes', 'Cuculiformes'), ('Apodiformes', 'Apodiformes'), ('Caprimulgiformes', 'Caprimulgiformes'), ('Coraciiformes', 'Coraciiformes'), ('Pelecaniformes', 'Pelecaniformes'), ('Ciconiiformes', 'Ciconiiformes'), ('Phoenicopteriformes', 'Phoenicopteriformes'), ('Podicipediformes', 'Podicipediformes'), ('Other', 'Other')], max_length=50)),
                ('family', models.CharField(choices=[('Felidae', 'Felidae'), ('Canidae', 'Canidae'), ('Ursidae', 'Ursidae'), ('Mustelidae', 'Mustelidae'), ('Viverridae', 'Viverridae'), ('Nandiniidae', 'Nandiniidae'), ('Prionodontidae', 'Prionodontidae'), ('Hyaenidae', 'Hyaenidae'), ('Ailuridae', 'Ailuridae'), ('Mephitidae', 'Mephitidae'), ('Procyonidae', 'Procyonidae'), ('Pandidae', 'Pandidae'), ('Otariidae', 'Otariidae'), ('Phocidae', 'Phocidae'), ('Odobenidae', 'Odobenidae'), ('Equidae', 'Equidae'), ('Tayassuidae', 'Tayassuidae'), ('Suidae', 'Suidae'), ('Camelidae', 'Camelidae'), ('Cervidae', 'Cervidae'), ('Bovidae', 'Bovidae'), ('Antilocapridae', 'Antilocapridae'), ('Giraffidae', 'Giraffidae'), ('Other', 'Other')], max_length=50)),
                ('genus', models.CharField(choices=[('Felis', 'Felis'), ('Canis', 'Canis'), ('Ursus', 'Ursus'), ('Mustela', 'Mustela'), ('Viverra', 'Viverra'), ('Nandinia', 'Nandinia'), ('Prionodon', 'Prionodon'), ('Crocuta', 'Crocuta'), ('Ailurus', 'Ailurus'), ('Mephitis', 'Mephitis'), ('Procyon', 'Procyon'), ('Ailuropoda', 'Ailuropoda'), ('Callorhinus', 'Callorhinus'), ('Mirounga', 'Mirounga'), ('Odobenus', 'Odobenus'), ('Equus', 'Equus'), ('Tayassu', 'Tayassu'), ('Sus', 'Sus'), ('Camelus', 'Camelus'), ('Cervus', 'Cervus'), ('Bos', 'Bos'), ('Antilocapra', 'Antilocapra'), ('Giraffa', 'Giraffa'), ('Other', 'Other')], max_length=50)),
                ('species', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('adopted', 'Adopted')], default='healthy', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taxonomicrank')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('news', 'News'), ('event', 'Event'), ('announcement', 'Announcement'), ('blog', 'Blog'), ('other', 'Other')], max_length=50, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.animal')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('hobbies', models.BinaryField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('temporary leave', 'Temporary Leave')], default='active', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
