# Generated by Django 5.1.6 on 2025-03-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_taxonomicrank_class_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': [('ceo_view_note', 'Can view notes sent to the CEO board.'), ('ceo_add_note', 'Can add notes to the CEO board.'), ('ceo_delete_note', 'Can delete notes sent to the CEO board.'), ('hr_view_note', 'Can view notes sent to the HR board.'), ('hr_add_note', 'Can add notes to the HR board.'), ('hr_delete_note', 'Can delete notes sent to the HR board.'), ('board_view_note', 'Can view notes sent to the Board of Directors board.'), ('board_add_note', 'Can add notes to the Board of Directors board.'), ('board_delete_note', 'Can delete notes sent to the Board of Directors board.'), ('volunteer_view_note', 'Can view notes sent to the Volunteer board.'), ('volunteer_add_note', 'Can add notes to the Volunteer board.'), ('volunteer_delete_note', 'Can delete notes sent to the Volunteer board.')]},
        ),
        migrations.AddField(
            model_name='note',
            name='boards',
            field=models.JSONField(default=list),
        ),
    ]
