# Generated by Django 5.1.6 on 2025-03-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_options_note_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('usd_amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='needs_review',
            field=models.BooleanField(default=True),
        ),
    ]
