from django.db import models


class TaxonomicDomain(models.TextChoices):
    ARCHAEA = "Archaea"
    BACTERIA = "Bacteria"
    EUKARYA = "Eukarya"
    OTHER = "Other"


class TaxonomicKingdom(models.TextChoices):
    ANIMALIA = "Animalia"
    PLANTAE = "Plantae"
    FUNGI = "Fungi"
    PROTISTA = "Protista"
    MONERA = "Monera"
    OTHER = "Other"


class TaxonomicPhylum(models.TextChoices):
    CHORDATA = "Chordata"
    ARTHROPODA = "Arthropoda"
    MOLLUSCA = "Mollusca"
    ECHINODERMATA = "Echinodermata"
    PORIFERA = "Porifera"
    CNIDARIA = "Cnidaria"
    PLATYHELMINTHES = "Platyhelminthes"
    NEMATODA = "Nematoda"
    ANNELIDA = "Annelida"
    BRYOZOA = "Bryozoa"
    BRACHIOPODA = "Brachiopoda"
    CHAETOGNATHA = "Chaetognatha"
    ECHIURA = "Echiura"
    HEMICHORDATA = "Hemichordata"
    NEMERTEA = "Nemertea"
    ONYCHOPHORA = "Onychophora"
    ORTHONECTIDA = "Orthonectida"
    PHORONIDA = "Phoronida"
    ROTIFERA = "Rotifera"
    TARDIGRADA = "Tardigrada"
    XENOTURBELLIDA = "Xenoturbellida"
    OTHER = "Other"


class TaxonomicClass(models.TextChoices):
    MAMMALIA = "Mammalia"
    AVES = "Aves"
    REPTILIA = "Reptilia"
    AMPHIBIA = "Amphibia"
    ACTINOPTERYGII = "Actinopterygii"
    CHONDRICHTHYES = "Chondrichthyes"
    MYXINI = "Myxini"
    PETROMYZON = "Petromyzon"
    CEPHALASPIDOMORPHI = "Cephalaspidomorphi"
    INSECTA = "Insecta"
    ARACHNIDA = "Arachnida"
    CRUSTACEA = "Crustacea"
    MALACOSTRACA = "Malacostraca"
    MAXILLOPODA = "Maxillopoda"
    BRANCHIOPODA = "Branchiopoda"
    OSTRACODA = "Ostracoda"
    CEPHALOPODA = "Cephalopoda"
    GASTROPODA = "Gastropoda"
    BIVALVIA = "Bivalvia"
    SCAPHOPODA = "Scaphopoda"
    POLYPLACOPHORA = "Polyplacophora"
    MONOPLACOPHORA = "Monoplacophora"
    OTHER = "Other"


class TaxonomicOrder(models.TextChoices):
    CARNIVORA = "Carnivora"
    PRIMATES = "Primates"
    RODENTIA = "Rodentia"
    CHIROPTERA = "Chiroptera"
    PASSERIFORMES = "Passeriformes"
    GALLIFORMES = "Galliformes"
    ANSERIFORMES = "Anseriformes"
    CHARADRIIFORMES = "Charadriiformes"
    FALCONIFORMES = "Falconiformes"
    STRIGIFORMES = "Strigiformes"
    PICIFORMES = "Piciformes"
    PSITTACIFORMES = "Psittaciformes"
    COLUMBIFORMES = "Columbiformes"
    CUCULIFORMES = "Cuculiformes"
    APODIFORMES = "Apodiformes"
    CAPRIMULGIFORMES = "Caprimulgiformes"
    CORACIIFORMES = "Coraciiformes"
    PELECANIFORMES = "Pelecaniformes"
    CICONIIFORMES = "Ciconiiformes"
    PHOENICOPTERIFORMES = "Phoenicopteriformes"
    PODICIPEDIFORMES = "Podicipediformes"
    OTHER = "Other"


class TaxonomicFamily(models.TextChoices):
    FELIDAE = "Felidae"
    CANIDAE = "Canidae"
    URSIDAE = "Ursidae"
    MUSTELIDAE = "Mustelidae"
    VIVERRIDAE = "Viverridae"
    NANDINIIDAE = "Nandiniidae"
    PRIONODONTIDAE = "Prionodontidae"
    HYAENIDAE = "Hyaenidae"
    AILURIDAE = "Ailuridae"
    MEPHITIDAE = "Mephitidae"
    PROCYONIDAE = "Procyonidae"
    PANDIDAE = "Pandidae"
    OTARIIDAE = "Otariidae"
    PHOCIDAE = "Phocidae"
    ODOBENIDAE = "Odobenidae"
    EQUIDAE = "Equidae"
    TAYASSUIDAE = "Tayassuidae"
    SUIDAE = "Suidae"
    CAMELIDAE = "Camelidae"
    CERVIDAE = "Cervidae"
    BOVIDAE = "Bovidae"
    ANTILOCAPRIDAE = "Antilocapridae"
    GIRAFFIDAE = "Giraffidae"
    OTHER = "Other"


class TaxonomicGenus(models.TextChoices):
    FELIS = "Felis"
    CANIS = "Canis"
    URSUS = "Ursus"
    MUSTELA = "Mustela"
    VIVERRA = "Viverra"
    NANDINIA = "Nandinia"
    PRIONODON = "Prionodon"
    CROCUTA = "Crocuta"
    AILURUS = "Ailurus"
    MEPHITIS = "Mephitis"
    PROCYON = "Procyon"
    AILUROPODA = "Ailuropoda"
    CALLORHINUS = "Callorhinus"
    MIROUNGA = "Mirounga"
    ODOBENUS = "Odobenus"
    EQUUS = "Equus"
    TAYASSU = "Tayassu"
    SUS = "Sus"
    CAMELUS = "Camelus"
    CERVUS = "Cervus"
    BOS = "Bos"
    ANTILOCAPRA = "Antilocapra"
    GIRAFFA = "Giraffa"
    OTHER = "Other"
